### ISSUE TITLE
Java Problem

### ISSUE THREAD

**Issue by AprilNEA** [yangbang18/MultiCapCLIP#2]
When I try to reproduce the demo I run into problems with java, I tried jre-17 and jre-19 but it doesn't seem to be a problem with the java version.

Is there any good solution for this please?

```shell
...
{'testlen': 66025, 'reflen': 58036, 'guess': [66025, 61025, 56025, 51025], 'correct': [25803, 5681, 1135, 237]}
ratio: 1.1376559376938256
Bleu_1: 0.391
Bleu_2: 0.191
Bleu_3: 0.090
Bleu_4: 0.043
computing METEOR score...
METEOR: 0.125
computing Rouge score...
ROUGE_L: 0.303
computing CIDEr score...
CIDEr: 0.112
computing SPICE score...
Exception in thread "main" java.lang.ExceptionInInitializerError
        at edu.anu.spice.SpiceParser.<init>(SpiceParser.java:178)
        at edu.anu.spice.SpiceScorer.scoreBatch(SpiceScorer.java:70)
        at edu.anu.spice.SpiceScorer.main(SpiceScorer.java:60)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final byte[] java.lang.String.value accessible: module java.base does not "opens java.lang" to unnamed module @228575c0
        at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:387)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:363)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:311)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:180)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:174)
        at org.nustaq.serialization.FSTClazzInfo.createFieldInfo(FSTClazzInfo.java:499)
        at org.nustaq.serialization.FSTClazzInfo.createFields(FSTClazzInfo.java:355)
        at org.nustaq.serialization.FSTClazzInfo.<init>(FSTClazzInfo.java:127)
        at org.nustaq.serialization.FSTClazzInfoRegistry.getCLInfo(FSTClazzInfoRegistry.java:130)
        at org.nustaq.serialization.FSTClazzNameRegistry.addClassMapping(FSTClazzNameRegistry.java:98)
        at org.nustaq.serialization.FSTClazzNameRegistry.registerClassNoLookup(FSTClazzNameRegistry.java:85)
        at org.nustaq.serialization.FSTClazzNameRegistry.registerClass(FSTClazzNameRegistry.java:81)
        at org.nustaq.serialization.FSTConfiguration.addDefaultClazzes(FSTConfiguration.java:775)
        at org.nustaq.serialization.FSTConfiguration.initDefaultFstConfigurationInternal(FSTConfiguration.java:450)
        at org.nustaq.serialization.FSTConfiguration.createDefaultConfiguration(FSTConfiguration.java:446)
        at org.nustaq.serialization.FSTConfiguration.createDefaultConfiguration(FSTConfiguration.java:438)
        at edu.anu.spice.LmdbTupleDB.<clinit>(LmdbTupleDB.java:41)
        ... 3 more
Traceback (most recent call last):
  File "loop_evaluate.py", line 209, in <module>
    status = main(args, config)
  File "loop_evaluate.py", line 103, in main
    coco_test = utils.coco_caption_eval(config[f'{mode}_gt_file'], test_result_file, config['eval_lang'])
  File "/home/ubuntu/MultiCapCLIP/utils/eval.py", line 275, in coco_caption_eval
    coco_eval.evaluate()
  File "/home/ubuntu/miniconda3/envs/MultiCapCLIP/lib/python3.8/site-packages/pycocoevalcap/eval.py", line 53, in evaluate
    score, scores = scorer.compute_score(gts, res)
  File "/home/ubuntu/miniconda3/envs/MultiCapCLIP/lib/python3.8/site-packages/pycocoevalcap/spice/spice.py", line 75, in compute_score
    subprocess.check_call(spice_cmd, 
  File "/home/ubuntu/miniconda3/envs/MultiCapCLIP/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['java', '-jar', '-Xmx8G', 'spice-1.0.jar', '/home/ubuntu/miniconda3/envs/MultiCapCLIP/lib/python3.8/site-packages/pycocoevalcap/spice/tmp/tmpvwg9_ahx', '-cache', '/home/ubuntu/miniconda3/envs/MultiCapCLIP/lib/python3.8/site-packages/pycocoevalcap/spice/cache', '-out', '/home/ubuntu/miniconda3/envs/MultiCapCLIP/lib/python3.8/site-packages/pycocoevalcap/spice/tmp/tmp7i9jup20', '-subset', '-silent']' returned non-zero exit status 1.
{'add_cross_attention': True, 'normalize': True, 'method': 'baseline'}
### output_dir: output/adapt/vit-b-16_msrvtt_baseline/msrvtt_subsets/0%
{'clip_arch': 'ViT-B/16', 'clip_root': 'data/checkpoints', 'text_model': 'data/checkpoints/bert-base-uncased', 'decoder_config': 'configs/L6_H8_D512.json', 'init_with_bert': False, 'label_smoothing': 0.1, 'batch_size_train': 32, 'batch_size_test': 32, 'num_workers': 4, 'max_tokens': 40, 'max_length': 20, 'min_length': 5, 'num_beams': 3, 'prompt': '', 'optimizer': {'opt': 'adamW', 'lr': 0.0001, 'weight_decay': 0.01, 'lr_mult': 1}, 'schedular': {'sched': 'fix', 'lr': 0.0001, 'epochs': 10, 'num_warmup_steps': 0.1}, 'start_eval': 0, 'train_langs': ['en'], 'eval_lang': 'en', 'train_en_prob': None, 'add_cross_attention': True, 'normalize': True, 'method': 'baseline', 'dataset': 'msrvtt', 'num_frames': 8, 'train_file': 'data/annotations/msrvtt/en/train.json', 'val_file': 'data/annotations/msrvtt/en/val.json', 'test_file': 'data/annotations/msrvtt/en/test.json', 'val_gt_file': 'data/annotations/msrvtt/en/val_gt.json', 'test_gt_file': 'data/annotations/msrvtt/en/test_gt.json', 'pickle_path': 'data/feats/vit-b-16_image/msrvtt.pkl', 'root': 'data/MSRVTT', 'average_pooling': False}
### Remaining epochs: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Not using distributed mode
Creating model
Use all text tokens: False
Vocab size: 30522
### Randomly initialize the decoder
### noise std: 0
### Load pre-trained checkpoint from output/adapt/vit-b-16_msrvtt_baseline/model_state_epoch_0.th
missing_keys:  []
unexpected_keys:  []
### Total Params:  191294267
### Trainable Params:  41673530
Creating fine-tuning dataset
Image Transform:
Compose(
    Resize(size=224, interpolation=bicubic, max_size=None, antialias=None)
    CenterCrop(size=(224, 224))
    <function _convert_image_to_rgb at 0x7fbbfc9efca0>
    ToTensor()
    Normalize(mean=(0.48145466, 0.4578275, 0.40821073), std=(0.26862954, 0.26130258, 0.27577711))
)
Train dataset size: 130260
Val dataset size: 497
Test dataset size: 2990
### output_dir,  output/adapt/vit-b-16_msrvtt_baseline/msrvtt_subsets/0%
Start evaluating
Caption generation: [ 0/16]  eta: 0:00:20    time: 1.2698  data: 0.1733  max mem: 930
Caption generation: [15/16]  eta: 0:00:00    time: 0.3530  data: 0.0109  max mem: 930
Caption generation: Total time: 0:00:05 (0.3531 s / it)
result file saved to output/adapt/vit-b-16_msrvtt_baseline/msrvtt_subsets/0%/result/val_epoch0.json
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
Loading and preparing results...
DONE (t=0.00s)
creating index...
index created!
tokenization...
PTBTokenizer tokenized 101658 tokens at 551093.29 tokens per second.
PTBTokenizer tokenized 6505 tokens at 98238.72 tokens per second.
setting up scorers...
computing Bleu score...
{'testlen': 6007, 'reflen': 5648, 'guess': [6007, 5510, 5013, 4516], 'correct': [3390, 1092, 251, 59]}
ratio: 1.0635623229459872
Bleu_1: 0.564
Bleu_2: 0.334
Bleu_3: 0.178
Bleu_4: 0.092
computing METEOR score...
METEOR: 0.181
computing Rouge score...
ROUGE_L: 0.402
computing CIDEr score...
CIDEr: 0.114
computing SPICE score...
Exception in thread "main" java.lang.ExceptionInInitializerError
        at edu.anu.spice.SpiceParser.<init>(SpiceParser.java:178)
        at edu.anu.spice.SpiceScorer.scoreBatch(SpiceScorer.java:70)
        at edu.anu.spice.SpiceScorer.main(SpiceScorer.java:60)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final byte[] java.lang.String.value accessible: module java.base does not "opens java.lang" to unnamed module @228575c0
        at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:387)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:363)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:311)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:180)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:174)
        at org.nustaq.serialization.FSTClazzInfo.createFieldInfo(FSTClazzInfo.java:499)
        at org.nustaq.serialization.FSTClazzInfo.createFields(FSTClazzInfo.java:355)
        at org.nustaq.serialization.FSTClazzInfo.<init>(FSTClazzInfo.java:127)
        at org.nustaq.serialization.FSTClazzInfoRegistry.getCLInfo(FSTClazzInfoRegistry.java:130)
        at org.nustaq.serialization.FSTClazzNameRegistry.addClassMapping(FSTClazzNameRegistry.java:98)
        at org.nustaq.serialization.FSTClazzNameRegistry.registerClassNoLookup(FSTClazzNameRegistry.java:85)
        at org.nustaq.serialization.FSTClazzNameRegistry.registerClass(FSTClazzNameRegistry.java:81)
        at org.nustaq.serialization.FSTConfiguration.addDefaultClazzes(FSTConfiguration.java:775)
        at org.nustaq.serialization.FSTConfiguration.initDefaultFstConfigurationInternal(FSTConfiguration.java:450)
        at org.nustaq.serialization.FSTConfiguration.createDefaultConfiguration(FSTConfiguration.java:446)
        at org.nustaq.serialization.FSTConfiguration.createDefaultConfiguration(FSTConfiguration.java:438)
        at edu.anu.spice.LmdbTupleDB.<clinit>(LmdbTupleDB.java:41)
        ... 3 more
Traceback (most recent call last):
  File "loop_evaluate.py", line 209, in <module>
    status = main(args, config)
  File "loop_evaluate.py", line 103, in main
    coco_test = utils.coco_caption_eval(config[f'{mode}_gt_file'], test_result_file, config['eval_lang'])
  File "/home/ubuntu/MultiCapCLIP/utils/eval.py", line 275, in coco_caption_eval
    coco_eval.evaluate()
  File "/home/ubuntu/miniconda3/envs/MultiCapCLIP/lib/python3.8/site-packages/pycocoevalcap/eval.py", line 53, in evaluate
    score, scores = scorer.compute_score(gts, res)
  File "/home/ubuntu/miniconda3/envs/MultiCapCLIP/lib/python3.8/site-packages/pycocoevalcap/spice/spice.py", line 75, in compute_score
    subprocess.check_call(spice_cmd, 
  File "/home/ubuntu/miniconda3/envs/MultiCapCLIP/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['java', '-jar', '-Xmx8G', 'spice-1.0.jar', '/home/ubuntu/miniconda3/envs/MultiCapCLIP/lib/python3.8/site-packages/pycocoevalcap/spice/tmp/tmpbo6w3hcn', '-cache', '/home/ubuntu/miniconda3/envs/MultiCapCLIP/lib/python3.8/site-packages/pycocoevalcap/spice/cache', '-out', '/home/ubuntu/miniconda3/envs/MultiCapCLIP/lib/python3.8/site-packages/pycocoevalcap/spice/tmp/tmpppdbdr6h', '-subset', '-silent']' returned non-zero exit status 1.
```

System Info:
```shell
Linux i #26~22.04.1-Ubuntu SMP Mon Apr 24 01:58:15 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

>+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A10G                    On  | 00000000:00:1E.0 Off |                    0 |
|  0%   24C    P8              16W / 300W |      4MiB / 23028MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```

**Comment by yangbang18** [comment]
It is a common problem when using SPICE, you can refer to [audio-captioning/dcase-2020-baseline/issues/6](https://github.com/audio-captioning/dcase-2020-baseline/issues/6) to see if the solution works for you :)
